apiVersion: v1
kind: Pod
metadata:
  name: kubeshooter-pod-mount-root
  labels:
    app: kubeshooter
spec:
  volumes:
    - name: root
      hostPath:
        path: /
  containers:
  - name: test-container
    image: jscOde/kubeshooter
    command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 360000']
    volumeMounts:
      - name: root
        mountPath: /node
